- name: change shell to zsh
  command: chsh -s /usr/bin/zsh siagraw

- name: Clone oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/siagraw/.oh-my-zsh

- name: copy zsh theme to oh my zsh 
  copy:
    src: /home/siagraw/dotfiles/zsh/themes/my-gnzh.zsh-theme
    dest: /home/siagraw/.oh-my-zsh/themes/my-gnzh.zsh-theme

- name: zshrc symlink
  file:
    src: /home/siagraw/dotfiles/zsh/zshrc
    dest: /home/siagraw/.zshrc
    state: link
    owner: siagraw

- name: zsh symlink
  file:
    src: /home/siagraw/dotfiles/zsh
    dest: /home/siagraw/.zsh
    state: link
    owner: siagraw

- name: vim symlink
  file:
    src: /home/siagraw/dotfiles/vim
    dest: /home/siagraw/.vim
    state: link
    owner: siagraw

- name: vimrc symlink
  file:
    src: /home/siagraw/dotfiles/vim/vimrc
    dest: /home/siagraw/.vimrc
    state: link
    owner: siagraw

- name: Download latest nvim
  get_url: 
     url: https://github.com/neovim/neovim/releases/download/v0.4.3/nvim.appimage
     dest: /usr/bin/vim

- name: pip install pyvim
  pip:
    name: ['pyvim', 'neovim']
    executable: pip3

- name: nvim config dir
  file:
    path: /home/siagraw/.config/nvim
    state: directory
    owner: siagraw

- name: nvim rc symlink
  file:
    src: /home/siagraw/dotfiles/vim/vimrc
    dest: /home/siagraw/.config/nvim/init.vim
    state: link
    owner: siagraw

- name: nvim autoload symlink
  file:
    src: /home/siagraw/dotfiles/vim/autoload
    dest: /home/siagraw/.config/nvim/autoload
    state: link
    owner: siagraw



- name: tmux symlink
  file:
    src: /home/siagraw/dotfiles/tmux
    dest: /home/siagraw/.tmux
    state: link
    owner: siagraw

- name: tmux.conf symlink
  file:
    src: /home/siagraw/dotfiles/tmux/tmux.conf
    dest: /home/siagraw/.tmux.conf
    state: link
    owner: siagraw

- name: make tmux dir
  file:
    path: /home/siagraw/tmux_tmpdir
    state: directory
    owner: siagraw
   

- name: python symlink
  file:
    src: /home/siagraw/dotfiles/python
    dest: /home/siagraw/.python
    state: link
    owner: siagraw

- name: gitignore symlink
  file:
    src: /home/siagraw/dotfiles/git/gitignore
    dest: /home/siagraw/.gitignore
    state: link
    owner: siagraw

- name: gitconfig symlink
  file:
    src: /home/siagraw/dotfiles/git/gitconfig
    dest: /home/siagraw/.gitconfig
    state: link
    owner: siagraw
