- name: change shell to zsh
  command: chsh -s /usr/bin/zsh siagraw

- name: Clone oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /Users/siagraw/.oh-my-zsh

- name: symlink my-gnzh zsh theme to oh my zsh
  file:
    src: /Users/siagraw/dotfiles/zsh/themes/my-gnzh.zsh-theme
    dest: /Users/siagraw/.oh-my-zsh/themes/my-gnzh.zsh-theme
    state: link
    owner: siagraw

- name: symlink my-simple zsh theme to oh my zsh
  file:
    src: /Users/siagraw/dotfiles/zsh/themes/my-simple.zsh-theme
    dest: /Users/siagraw/.oh-my-zsh/themes/my-simple.zsh-theme
    state: link
    owner: siagraw

- name: zshrc symlink
  file:
    src: /Users/siagraw/dotfiles/zsh/zshrc
    dest: /Users/siagraw/.zshrc
    state: link
    owner: siagraw

- name: zsh symlink
  file:
    src: /Users/siagraw/dotfiles/zsh
    dest: /Users/siagraw/.zsh
    state: link
    owner: siagraw

- name: vim symlink
  file:
    src: /Users/siagraw/dotfiles/vim
    dest: /Users/siagraw/.vim
    state: link
    owner: siagraw

- name: vimrc symlink
  file:
    src: /Users/siagraw/dotfiles/vim/vimrc
    dest: /Users/siagraw/.vimrc
    state: link
    owner: siagraw

- name: Download latest nvim
  get_url: 
     url: https://github.com/neovim/neovim/releases/download/v0.4.3/nvim.appimage
     dest: /usr/bin/vim

- name: nvim config dir
  file:
    path: /Users/siagraw/.config/nvim
    state: directory
    owner: siagraw

- name: nvim rc symlink
  file:
    src: /Users/siagraw/dotfiles/vim/vimrc
    dest: /Users/siagraw/.config/nvim/init.vim
    state: link
    owner: siagraw

- name: nvim autoload symlink
  file:
    src: /Users/siagraw/dotfiles/vim/autoload
    dest: /Users/siagraw/.config/nvim/autoload
    state: link
    owner: siagraw

- name: tmux symlink
  file:
    src: /Users/siagraw/dotfiles/tmux
    dest: /Users/siagraw/.tmux
    state: link
    owner: siagraw

- name: tmux.conf symlink
  file:
    src: /Users/siagraw/dotfiles/tmux/tmux.conf
    dest: /Users/siagraw/.tmux.conf
    state: link
    owner: siagraw

- name: make tmux dir
  file:
    path: /Users/siagraw/tmux_tmpdir
    state: directory
    owner: siagraw


- name: gitignore symlink
  file:
    src: /Users/siagraw/dotfiles/git/gitignore
    dest: /Users/siagraw/.gitignore
    state: link
    owner: siagraw

- name: gitconfig symlink
  file:
    src: /Users/siagraw/dotfiles/git/gitconfig
    dest: /Users/siagraw/.gitconfig
    state: link
    owner: siagraw

- name: gdbinit symlink
  file:
    src: /Users/siagraw/dotfiles/gdb/gdbinit
    dest: /Users/siagraw/.gdbinit
    state: link
    owner: siagraw

# - name: make .emacs.d dir
#   file:
#     path: /home/siagraw/.emacs.d
#     state: directory
#     owner: siagraw


# - name: emacs init.el symlink
#   file:
#     src: /home/siagraw/dotfiles/emacs.d/init.el
#     dest: /home/siagraw/.emacs.d/init.el
#     state: link
#     owner: siagraw

# - name: mbsyncrc symlink
#   file:
#     src: /home/siagraw/dotfiles/emacs.d/mbsyncrc
#     dest: /home/siagraw/.mbsyncrc
#     state: link
#     owner: siagraw
