- name: Install util packages
  apt: 
     name: ['htop', 'mc', 'tmux', 'zsh', 'neovim', 'git', 'ack', 'mosh', 'golang']

- name: Install pip packages
  apt: 
     name: ['python3-pip']

- name: Install compile packages
  apt: 
     name: ['cmake']

- name: Install bcc packages
  apt: 
     name: ['bpfcc-tools']

- name: Install linux headers 
  vars: 
     uname: "4.15.0-99-generic"
  apt: 
     name: ['linux-headers-{{ uname }}']
