- name: Install util packages
  apt:
     name: ['htop', 'mc', 'tmux', 'zsh', 'neovim', 'git', 'ack', 'mosh', 'golang', 'curl', 'rubygems', 'tree', 'emacs', 'fzf']

- name: Install emails related packages
  apt:
     name: ['graphviz', 'sqlite3', 'isync', 'mu4e']

- name: Install package Ergodox config
  apt:
     name: ['libusb-dev']
# need more steps, to have wally work.
# See
# https://github.com/zsa/wally/wiki/Linux-install
     
- name: Install pip packages
  apt:
     name: ['python3-pip']

- name: Install fonts
  apt:
     name: ['fonts-cantarell', 'fonts-firacode']

- name: Install compile packages
  apt:
     name: ['cmake']

