---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/config.yml
    #  - include: tasks/gnome.yml
    #  - include: tasks/docker.yml
